In [1]:
import tensorflow as tf
print(tf.__version__)
from tensorflow.keras.preprocessing.text import one_hot


2.15.0


In [17]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [18]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [19]:
## Define the vocabulary size
voc_size=10000

In [20]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [21]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[5832, 8210, 4341, 2026],
 [5832, 8210, 4341, 8179],
 [5832, 770, 4341, 1005],
 [3617, 4262, 3890, 1761, 2752],
 [3617, 4262, 3890, 1761, 9623],
 [6420, 5832, 6838, 4341, 3063],
 [9093, 4974, 1118, 1761]]

In [22]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [23]:
import numpy as np

In [24]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 5832 8210 4341 2026]
 [   0    0    0    0 5832 8210 4341 8179]
 [   0    0    0    0 5832  770 4341 1005]
 [   0    0    0 3617 4262 3890 1761 2752]
 [   0    0    0 3617 4262 3890 1761 9623]
 [   0    0    0 6420 5832 6838 4341 3063]
 [   0    0    0    0 9093 4974 1118 1761]]


In [25]:
## feature representation
dim=10

In [26]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [27]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [28]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 95ms/step


array([[[ 9.00626183e-03, -3.41799743e-02, -2.47203838e-02,
          1.58356540e-02, -9.60222632e-03,  2.59283446e-02,
          6.31051138e-03, -2.11663730e-02, -3.13471705e-02,
          3.40192951e-02],
        [ 9.00626183e-03, -3.41799743e-02, -2.47203838e-02,
          1.58356540e-02, -9.60222632e-03,  2.59283446e-02,
          6.31051138e-03, -2.11663730e-02, -3.13471705e-02,
          3.40192951e-02],
        [ 9.00626183e-03, -3.41799743e-02, -2.47203838e-02,
          1.58356540e-02, -9.60222632e-03,  2.59283446e-02,
          6.31051138e-03, -2.11663730e-02, -3.13471705e-02,
          3.40192951e-02],
        [ 9.00626183e-03, -3.41799743e-02, -2.47203838e-02,
          1.58356540e-02, -9.60222632e-03,  2.59283446e-02,
          6.31051138e-03, -2.11663730e-02, -3.13471705e-02,
          3.40192951e-02],
        [ 2.61318423e-02, -4.78768125e-02,  5.97809628e-03,
          4.58975695e-02, -3.34604271e-02, -1.15194805e-02,
          3.16578783e-02, -3.29676419e-02,  3.611756

In [29]:
embedded_docs[0]

array([   0,    0,    0,    0, 5832, 8210, 4341, 2026])

In [30]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 84ms/step


array([[ 9.00626183e-03, -3.41799743e-02, -2.47203838e-02,
         1.58356540e-02, -9.60222632e-03,  2.59283446e-02,
         6.31051138e-03, -2.11663730e-02, -3.13471705e-02,
         3.40192951e-02],
       [ 9.00626183e-03, -3.41799743e-02, -2.47203838e-02,
         1.58356540e-02, -9.60222632e-03,  2.59283446e-02,
         6.31051138e-03, -2.11663730e-02, -3.13471705e-02,
         3.40192951e-02],
       [ 9.00626183e-03, -3.41799743e-02, -2.47203838e-02,
         1.58356540e-02, -9.60222632e-03,  2.59283446e-02,
         6.31051138e-03, -2.11663730e-02, -3.13471705e-02,
         3.40192951e-02],
       [ 9.00626183e-03, -3.41799743e-02, -2.47203838e-02,
         1.58356540e-02, -9.60222632e-03,  2.59283446e-02,
         6.31051138e-03, -2.11663730e-02, -3.13471705e-02,
         3.40192951e-02],
       [ 2.61318423e-02, -4.78768125e-02,  5.97809628e-03,
         4.58975695e-02, -3.34604271e-02, -1.15194805e-02,
         3.16578783e-02, -3.29676419e-02,  3.61175649e-02,
        -2.